### ISSUE TITLE
Option for non round corners

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#1723]
It would be good to have an option for non round corners

**Comment by limonte** [comment]
```css
.border-radius-0 {
  border-radius: 0;
}
```

```js
Swal.fire({
  ...
  customClass: {
    popup: 'border-radius-0'
  }
```

https://sweetalert2.github.io/#custom-class

**Comment by rocketlaunchr-cto** [comment]
It gets over-ridden by `.swal2-popup`

**Comment by pjebs** [comment]
@limonte `border-radius-0` gets applied but it gets over-ridden by `.swal2-popup`

**Comment by limonte** [comment]
No.

https://verbena-week.glitch.me/

**Comment by pjebs** [comment]
In your example, for some reason `border-radius-0` has higher precedence that `swal2-popup`.

For my code, the exact same `customClass: {
    popup: 'border-radius-0'
  }` has the precedence the other way around.

**Comment by pjebs** [comment]
Could there be an element of randomness involved?

**Comment by pjebs** [comment]
or an undefined order

**Comment by pjebs** [comment]
No prob. I had a css precedence issue.

**Comment by KBeDeveloper** [comment]
If you want to apply this to all **swal2** modals, just use:

```css
.swal2-popup.swal2-modal {
	-webkit-border-radius: 0 !important;
	-moz-border-radius: 0 !important;
	border-radius: 0 !important;
}
```
