### ISSUE TITLE
z index

### ISSUE THREAD

**Issue by juancavf** [sweetalert2/sweetalert2#2276]
Hello, how can i modify the z-index from the alerts?

**Comment by limonte** [comment]
```js
Swal.fire({
  ...
  customClass: {
    container: 'custom-z-index',
  }
})
```

```css
.custom-z-index {
  z-index: 9999 !important
}
```
