### ISSUE TITLE
About swal2-progress-steps background class

### ISSUE THREAD

**Issue by SuperManito** [sweetalert2/sweetalert2#2436]
When the background CSS is set, the background of this `swal2-progress-steps` will also change. When the setting background is not pure color I think it is very ugly. Maybe it should be set to `transparent`. 

- I found a way to set it

  ```css
  .swal2-progress-steps {
    background: transparent;
  }
  ```
