### ISSUE TITLE
Change default font-family to system UI font

### ISSUE THREAD

**Issue by sloria** [sweetalert2/sweetalert2#846]
Currently, the font-family for dialogs is set to Helvetica Neue.

```css
.swal2-popup {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

I'm not sure this is desired; I want the popup's font to be consistent with the rest of my app, so I end up overriding the above rule:

```css
.swal2-popup {
  font-family: inherit;
}
```

Would it make sense to remove the `font-family` property so that it will be inherited by default?

**Comment by limonte** [comment]
> I'm not sure this is desired

This is desired. You're able to override the font-family for SweetAlert2 either in CSS as you mentioned or with SCSS variable `$swal2-font`.

**Comment by sloria** [comment]
@limonte Would you be open to changing the default to the system UI font?

```css
.swal2-popup {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", 
        "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
}
```

This seems a more sensible default than Helvetica Neue.

If you're up for it, I can send a PR.

**Comment by limonte** [comment]
@sloria please do so, I'd like to hear contributor's opinion on this. For me, it looks like a breaking change, which could be included in the next major.

**Comment by sloria** [comment]
@limonte Done in #847. Let me know if there is anything to be addressed.

**Comment by limonte** [comment]
There's the interesting detail at least in Chrome:

![](https://i.imgur.com/B8RVM9C.png)

Buttons still have Arial font. Should we do something about that or keep the default browser behavior?

**Comment by limonte** [comment]
> Buttons still have Arial font. Should we do something about that or keep the default browser behavior?

In case of <button> tags, font-family is not inherited automatically. That's a default browser's behavior, let's not change it.

**Comment by Un-knownCoder** [comment]
I think the only way to chenge the font in that modal is:
```css
.swal2-popup.swal2-modal.swal2-show {
  font-family: 'Source Sans Pro' /*or any other font*/ ;
}
```
