### ISSUE TITLE
Swal is open smaller when used with bootstrap

### ISSUE THREAD

**Issue by brabao** [sweetalert2/sweetalert2#855]
Swal (`7.7.0`) is open smaller when used with bootstrap (`3.3.7`)

[Example](https://jsbin.com/fuguderizi/2/edit?html,output)

Does anyone know how to fixthis?
Thanks fo any help

**Comment by limonte** [comment]
Duplicate of #834

Reason: Bootstrap 3 is setting `font-size: 10px` for `html`.

Solution: 

```css
.swal2-popup {
  font-size: 1.6rem !important;
}
```

**Comment by epexa** [comment]
my solution:
```css
.swal2-container {
  zoom: 1.5;
}
```
